export const HOME = "home"
export const SPLASH = "splash"
export const SIGNUP = "signup"
export const LOGIN = "login"
export const MAIN = "main"
export const PROFILE = "profile"
export const TASK = "task"
export const LOGOUT = "logout"
export const REGISTER = "register"
export const VERIFY = "verify"
export const VERIFIED = "verified"
//Admin Side
export const ADMIN_HOME="ADMIN_HOME"
export const ADMIN_USER="ADMIN_USER"
export const ADMIN_EMPLOYEES="ADMIN_EMPLOYEES"
export const ADMIN_TASK="ADMIN_TASK"
export const ADMIN_ADD_EMPLOYEE="ADMIN_ADD_EMPLOYEE"